//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSys.Localizations.Resources.Lookup {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmergencyImages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmergencyImages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HRSys.Localizations.Resources.Lookup.EmergencyImages", typeof(EmergencyImages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAI0AAACoCAYAAADdP20gAAAABHNCSVQICAgIfAhkiAAAIABJREFUeF7tXXmcHFW1/k51TzITCFsgCcFEtmAQlS0PkumqSiIoQbYgRCCZ7kQWBREQcQFZHquggiCyyZ6umQHM8wUEf4BPSKZv9RAwrC6AYU0kkgVkMZnJTHed9zvVXZOmmZmuXqd7Zu4/8Evf9dxvbt3lO98hDKcBs8C8eHy/gONMBtEu5GACAxOI0v8FJkjHGFhDwBow3mFi9//l35KatrI1FHphIDpPA9HoUG3zpKUrdgwGNh9K4NlMmE3AuKJswfwuQI9Dw6MJ5j+2Gsa/i6rPZ+Fh0Pg0VKHZFtj2Pg7wDXJ4NogOKrQef+U4zsBjGtGSRbr+N39l8s81DJr8bearRFipSQCuJNB8AJqvQqXL5DC4JRAMXnLv9Olvla7aVE3DoCmxRd1PULDjYoBOJ2BEiavPqzoGug [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Image1 {
            get {
                return ResourceManager.GetString("Image1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJAAAACoCAYAAAAPb2d4AAAABHNCSVQICAgIfAhkiAAAIABJREFUeF7tfQmYFNW1/+9U98CMoIgbioKiYjSiuKDCdN2CyeKSmPfHz+AC0w361CQmURN9btEEn3HNP4m+xCySKHQNqMH3xKd5Li8vSFf1iE9U0OCGC0tEUVGIwIxMd5333equoWfoma7qru6uHrq+zw9w7j333HN/c++5556FUP8CIYHphjG8QVFOYss6CEwHMjCSgJFMmT+R+W89A+uJsR4K3mPm9ST/rSh/77Ks5xcI8WmlJ0OVHrA+XkYCs5mVt5PJE8B8OhhnADiFiELFyoeZ00RYysCTCvDEPFV9EURcLD23/eoAcispn9rFTHM6M74O5lOJaB+fyO5MhvkDgJ5i4j/rQiws1zh1AJVLsjl05W7zTjIZZcZNBBxcgSF7DsFYzcQ/PkxV588msvwcvw4gP6XZmxYzzU [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Image2 {
            get {
                return ResourceManager.GetString("Image2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKAAAACpCAYAAACswDblAAAABHNCSVQICAgIfAhkiAAAIABJREFUeF7tfXuQXOV15zn39ug12BICGxAxGbmMg2yzGjDrwEx3a1SpMpBkw2CHGINmNGSXxK7asgbbtWVv4iBqvcFJLWGI/7CzcazRzIAfJDCEeImddWnU3SOTrGJGfmGCY42ELczDeGT0ZLrv2Trfvd/t23fu47uvfojuKlsS/T3P9+vzne88Ebqfc4ICO/YfGNB0o88A2IQGXIoImwhgEwBtQoJNgHiKAI4hwTH+E5B+igDHDNKPGaR9/6Ft1z7bCkJgKybtzpmcAqMHDlxKVfpNRONGAvwNBHhjklEJ4AgQPKFp8ITxhjd8c3rr1pNJxlPt2wWgKqXaoN3o/Px1UKObCeAGRLgy2yXR/wXQntCN6sN7tm17Lqu5ugDMirIpjnvb/Hy/btD9CDCU4rBKQxHAawD0+RzRp/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Image3 {
            get {
                return ResourceManager.GetString("Image3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEsAAABLCAYAAAA4TnrqAAAABHNCSVQICAgIfAhkiAAACeVJREFUeF7dXGtsFNcV/s7suhiiFrWmIJxiQhKnuIJCgYDxzpigVoQKlZIfqJXxGlKVJlWlUikShUhUiWgDqRq1/KhSSprALqaKIgWqROIhVcW7s4aoJjEikmlIQzDBiQGnoq0JrnfnVGfIOOv17O68dvF6JGTjuef1zTn3nnvug3AHnpZk8otVivIgG8ZXwHQ3A7UE1DLd/onb//oY6CNGHxRcYeY+kv8rygfDhvH3Q5r2r3KrTuUQ+BSz8s9UahGYV4PxbQDLiCjkVTYzZ4hwmoFjCnD0gKq+CSL2ys8pXUnBatP1FmasAfMqIprmVCnX7Zg/Aug4FJyIqeoh1/QOCQIHS7zovVQqyoynCZjtUI/gmjHeZ+Jf3Keq7U8RGcExBgIFa6OurzUYvyJgXpBKeuHFjHNE/GRM01 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Image4 {
            get {
                return ResourceManager.GetString("Image4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAALEAAACoCAYAAACv8A+WAAAABHNCSVQICAgIfAhkiAAAHsxJREFUeF7tXQtsVNeZ/s7MGBObxARHsJBgcBIoTkNjCNECvteBXW1Jd1dbqFq1AeyQLakaqZuQRKtNoqYlTZVktUoC1WqTbUhjPJA+Um3cVbttWu1iPMMj5WFTKBAgYCBxeMcGbGzwzFn9d+aMr4eZuffO3Dtz7vgeCcWOz+M///nmn//8r8PgNY8DAJZt334Trkbv8/uit/EoJoHhVgY+iQOTGKff2WQOnGYcXQC6OONdDL5POP3u458MBgK7fjp37ulCMJMVYlFvTTk4sDwUuocBXwLwAAObD6AkW8o4wMF5O/Ox33HOf9uvKNveZSyS7XxWxnkgtsKtIui7vG3rYsaif8+ABwDc6tSWOPhnDOwPYPifAPBfP1GUS06t5YHYKc7KNC/nbPmWLV/zcf4CwKbnnzR+lgM/7B [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Image5 {
            get {
                return ResourceManager.GetString("Image5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAK8AAAC/CAYAAACIRIzuAAAABHNCSVQICAgIfAhkiAAAGENJREFUeF7tnX2MHNWRwKt6Zs3a5rD5CAZzODaxFXPCwjYWZ7zdA6ugIxw6Yp/OgmDPsuZDyulEbAvlYi4hWSe6hPuDw0RIuRwE1ju2AYHCcugERIlsT/cuhgO8viDZwdx5bStrPo81wp/b03V6Pdvr3tmZ6Z433TNvdqoFwma66lXX+01NvVfvvUbgq+k9sLa/fz7YcA1i7gpEnE0OzEaA2YQwG4CuQIKphDAEgENI8CcCGCINhjSAISenDW67cUV/PZyI9WiU26yvB1b3909tdZx2dOBWAvgmIsyvxiIC+AKBfk+kvZpLwG93tLUdrkZfWFmGN6ynGvy+zrfeusw5c+YOASsA3ogAU2N8pANE8Cpp8NI2XTfjaofhjcuziujt3Ll3Zi755UMA+EDMwJZ4YvodAmzaahjvRO [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Image6 {
            get {
                return ResourceManager.GetString("Image6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAKgAAACoCAYAAAB0S6W0AAAABHNCSVQICAgIfAhkiAAAHrNJREFUeF7tXX9w1dWVP+f7XgwJVCgR2GINoELBkRrQVoT3Ikx31N1Oa/ijuy4aZHa0W2dnC667rTi11dW6dnZccf9Ra60hIWytOyVu7Vqc2RXzXoCWX8GoKAiEoChgMAFCCHnf79k59+WGb16+773v9737/b730ntnnEhy7rn3nvv5nnvOufeei6DLn4QEVsRiXywzjK+RZX0ZCC8ngOkIMJ0w+ROS/x0jgGNIcAwM+JiIjiH/2zA+GrSsHRuj0c+DFhYG3aBuLxgJPEJkHGxrWwhEtwHBXwDAjYgYyrV1IjIRYTsB/N4AeH19JLIbEClXfm7raYC6lVSJ0K2Mx1cQwTeB6BZEvMy3bhN9CoCbCel3TdHoK361owHql2QD5Mva8lBbWz0RPIoAMwJsOtkUQSch/fiqSKT5EU [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Image7 {
            get {
                return ResourceManager.GetString("Image7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAJ8AAACmCAYAAADEbl2FAAAABHNCSVQICAgIfAhkiAAAF9BJREFUeF7tnXtwVFWex7/ndocQAgQJAxKWCAxRw8jycqYg6e4x45bu7NSMUDOWs0Aiu6OWllvK6D501lmf5Ujtog61q26No5gGLEcdcdSidLcWSHcQhpcICMgjJIEgr4QAeZHue7Z+N7mh07ndfbvvvd33dN/7D4+c+zvn/s4n5/x+5/zO7zA4j/AaWLp5S4XkkqfIQAmTMYkxlHCgBOAljKMEjHVyoIVxtNCfYPwkA1pk7mqBG/vWVFQcyYQSWCYqdeo0poGaLVsm8RD/G8bkH3KwWxkw2ohEzkHwbWASNvBRo+r8s2Z1GJGn910HPr2aynC5u+vqKjmkOzjw14xhprXN4f8LSBvgYu/UVlSctKouBz6rNGuS3MX19bNdMn+JAbeYJFK3GA50MfBVIWDFOq+3TfeLOgs68O [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Image8 {
            get {
                return ResourceManager.GetString("Image8", resourceCulture);
            }
        }
    }
}
