//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSys.Localizations.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HRSys.Localizations.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence Count.
        /// </summary>
        public static string AbsenceCount {
            get {
                return ResourceManager.GetString("AbsenceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to access the page that you requested.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        public static string AppointmentsLinkText {
            get {
                return ResourceManager.GetString("AppointmentsLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متاكد  ؟.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المرفقات.
        /// </summary>
        public static string Attachmnets {
            get {
                return ResourceManager.GetString("Attachmnets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع المرفق.
        /// </summary>
        public static string AttachmnetType {
            get {
                return ResourceManager.GetString("AttachmnetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackLinkText {
            get {
                return ResourceManager.GetString("BackLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boards.
        /// </summary>
        public static string BoardsLinkText {
            get {
                return ResourceManager.GetString("BoardsLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board Of Directors List.
        /// </summary>
        public static string BoardsList {
            get {
                return ResourceManager.GetString("BoardsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot delete,  this item used  in the system.
        /// </summary>
        public static string CannotDelete {
            get {
                return ResourceManager.GetString("CannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose File.
        /// </summary>
        public static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلغاء.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قائمة اللجان.
        /// </summary>
        public static string CommitteeList {
            get {
                return ResourceManager.GetString("CommitteeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committees.
        /// </summary>
        public static string CommitteesLinkText {
            get {
                return ResourceManager.GetString("CommitteesLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Meeting.
        /// </summary>
        public static string CreateNewMeeting {
            get {
                return ResourceManager.GetString("CreateNewMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ريال.
        /// </summary>
        public static string CurrencyLabel {
            get {
                return ResourceManager.GetString("CurrencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string DeleteCancelButtonText {
            get {
                return ResourceManager.GetString("DeleteCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string DeleteConfirmationText {
            get {
                return ResourceManager.GetString("DeleteConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data will be deleted.
        /// </summary>
        public static string DeleteConfirmationTitle {
            get {
                return ResourceManager.GetString("DeleteConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string DeleteConfirmButtonText {
            get {
                return ResourceManager.GetString("DeleteConfirmButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteLinkText {
            get {
                return ResourceManager.GetString("DeleteLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record hasn&apos;t been deleted successfully , because it has related records.
        /// </summary>
        public static string DeleteRelatedMemberErrorsMsg {
            get {
                return ResourceManager.GetString("DeleteRelatedMemberErrorsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record has been deleted successfully.
        /// </summary>
        public static string DeleteSuccessMsg {
            get {
                return ResourceManager.GetString("DeleteSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string DownloadLinkText {
            get {
                return ResourceManager.GetString("DownloadLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditLinkText {
            get {
                return ResourceManager.GetString("EditLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        public static string EmailValidateMsg {
            get {
                return ResourceManager.GetString("EmailValidateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Types.
        /// </summary>
        public static string EntityTypesLinkText {
            get {
                return ResourceManager.GetString("EntityTypesLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpLinkText {
            get {
                return ResourceManager.GetString("HelpLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity Number.
        /// </summary>
        public static string IdentityNumber {
            get {
                return ResourceManager.GetString("IdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Phone.
        /// </summary>
        public static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Username Or Password.
        /// </summary>
        public static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string LinkAddNewText {
            get {
                return ResourceManager.GetString("LinkAddNewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LogoutLinkText {
            get {
                return ResourceManager.GetString("LogoutLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Name.
        /// </summary>
        public static string MeetingName {
            get {
                return ResourceManager.GetString("MeetingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting No.
        /// </summary>
        public static string MeetingNo {
            get {
                return ResourceManager.GetString("MeetingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meeting Status.
        /// </summary>
        public static string MeetingStatus {
            get {
                return ResourceManager.GetString("MeetingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        public static string Member {
            get {
                return ResourceManager.GetString("Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memeber Count.
        /// </summary>
        public static string MemeberCount {
            get {
                return ResourceManager.GetString("MemeberCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memeber Name.
        /// </summary>
        public static string MemeberName {
            get {
                return ResourceManager.GetString("MemeberName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memeber Status.
        /// </summary>
        public static string MemeberStatus {
            get {
                return ResourceManager.GetString("MemeberStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NewLinkText {
            get {
                return ResourceManager.GetString("NewLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New meeting without framework.
        /// </summary>
        public static string NewMeetingNoFramework {
            get {
                return ResourceManager.GetString("NewMeetingNoFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to show.
        /// </summary>
        public static string NoDataShow {
            get {
                return ResourceManager.GetString("NoDataShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No meetings added.
        /// </summary>
        public static string NoMeeting {
            get {
                return ResourceManager.GetString("NoMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have new meeting.
        /// </summary>
        public static string NoNewMeeting {
            get {
                return ResourceManager.GetString("NoNewMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يحدد رئيس.
        /// </summary>
        public static string NoPresident {
            get {
                return ResourceManager.GetString("NoPresident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Results.
        /// </summary>
        public static string noResult {
            get {
                return ResourceManager.GetString("noResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقصى حد 3 ارقام.
        /// </summary>
        public static string NumberMaxLengthMsg {
            get {
                return ResourceManager.GetString("NumberMaxLengthMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation was done .
        /// </summary>
        public static string OperationDone {
            get {
                return ResourceManager.GetString("OperationDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string Organization {
            get {
                return ResourceManager.GetString("Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Name.
        /// </summary>
        public static string OrganizationName {
            get {
                return ResourceManager.GetString("OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختار جهة.
        /// </summary>
        public static string OrganizationRequired {
            get {
                return ResourceManager.GetString("OrganizationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to President.
        /// </summary>
        public static string President {
            get {
                return ResourceManager.GetString("President", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to President of Board of Director.
        /// </summary>
        public static string PresidentBoard {
            get {
                return ResourceManager.GetString("PresidentBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to President of Committee.
        /// </summary>
        public static string PresidentCommittee {
            get {
                return ResourceManager.GetString("PresidentCommittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to President of Preparstory Committee.
        /// </summary>
        public static string PresidentPreparCommittee {
            get {
                return ResourceManager.GetString("PresidentPreparCommittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to President of WorkTeam.
        /// </summary>
        public static string PresidentWorkTeam {
            get {
                return ResourceManager.GetString("PresidentWorkTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string PrivacyPolicyLinkText {
            get {
                return ResourceManager.GetString("PrivacyPolicyLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string ProfileLinkText {
            get {
                return ResourceManager.GetString("ProfileLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string ProjectsLinkText {
            get {
                return ResourceManager.GetString("ProjectsLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string RequiredfieldMsg {
            get {
                return ResourceManager.GetString("RequiredfieldMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should select one receiver at least .
        /// </summary>
        public static string RequiredReceiversfieldMsg {
            get {
                return ResourceManager.GetString("RequiredReceiversfieldMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should select one room at least.
        /// </summary>
        public static string RequiredRoomfieldMsg {
            get {
                return ResourceManager.GetString("RequiredRoomfieldMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientific Title.
        /// </summary>
        public static string ScientificTitle {
            get {
                return ResourceManager.GetString("ScientificTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بحث.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for.
        /// </summary>
        public static string SearchFieldText {
            get {
                return ResourceManager.GetString("SearchFieldText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for a user.
        /// </summary>
        public static string SearchUser {
            get {
                return ResourceManager.GetString("SearchUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد اكتر من سكرتير.
        /// </summary>
        public static string SecretaryCountMsg {
            get {
                return ResourceManager.GetString("SecretaryCountMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Please Select --.
        /// </summary>
        public static string SelectItem_PleaseSelectText {
            get {
                return ResourceManager.GetString("SelectItem_PleaseSelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sent succesfully.
        /// </summary>
        public static string SendAgendaMsg {
            get {
                return ResourceManager.GetString("SendAgendaMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent Successfully.
        /// </summary>
        public static string SendSuccessMsg {
            get {
                return ResourceManager.GetString("SendSuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsLinkText {
            get {
                return ResourceManager.GetString("SettingsLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان يكون تاريخ البداية اكبر من تاريخ النهاية.
        /// </summary>
        public static string StartDatemoreThenEndDate {
            get {
                return ResourceManager.GetString("StartDatemoreThenEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum 60 Characters.
        /// </summary>
        public static string StringMaxLengthMsg {
            get {
                return ResourceManager.GetString("StringMaxLengthMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Successfully.
        /// </summary>
        public static string SuccessMsg {
            get {
                return ResourceManager.GetString("SuccessMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SurName.
        /// </summary>
        public static string SurName {
            get {
                return ResourceManager.GetString("SurName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking.
        /// </summary>
        public static string TabCheckingText {
            get {
                return ResourceManager.GetString("TabCheckingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string TableOptionHeaderText {
            get {
                return ResourceManager.GetString("TableOptionHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic information.
        /// </summary>
        public static string TabMainInformationText {
            get {
                return ResourceManager.GetString("TabMainInformationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string TasksLinkText {
            get {
                return ResourceManager.GetString("TasksLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string UnDo {
            get {
                return ResourceManager.GetString("UnDo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task was closed in date  ({0}).
        /// </summary>
        public static string UpdateCloseTask {
            get {
                return ResourceManager.GetString("UpdateCloseTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date Was updated from {0} to {1}.
        /// </summary>
        public static string UpdatedDueDate {
            get {
                return ResourceManager.GetString("UpdatedDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to task was reopened  to edite in date  ({0}).
        /// </summary>
        public static string UpdateOpenTask {
            get {
                return ResourceManager.GetString("UpdateOpenTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Agreement.
        /// </summary>
        public static string UserAgreementLinkText {
            get {
                return ResourceManager.GetString("UserAgreementLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Guide.
        /// </summary>
        public static string UserGuide {
            get {
                return ResourceManager.GetString("UserGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Teams.
        /// </summary>
        public static string WorkTeamsList {
            get {
                return ResourceManager.GetString("WorkTeamsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لم يتم العثور على بيانات مطابقة.
        /// </summary>
        public static string ZeroRecords {
            get {
                return ResourceManager.GetString("ZeroRecords", resourceCulture);
            }
        }
    }
}
