//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRSys.Api {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HRSys.Api.ExceptionMessage", typeof(ExceptionMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to معلومات الحساب.
        /// </summary>
        public static string AccountInfo_ar {
            get {
                return ResourceManager.GetString("AccountInfo.ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Info.
        /// </summary>
        public static string AccountInfo_en {
            get {
                return ResourceManager.GetString("AccountInfo.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تفعيل الحساب.
        /// </summary>
        public static string ActivateAccount_ar {
            get {
                return ResourceManager.GetString("ActivateAccount.ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Account.
        /// </summary>
        public static string ActivateAccount_en {
            get {
                return ResourceManager.GetString("ActivateAccount.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Complaints.
        /// </summary>
        public static string AddComplaints_ar {
            get {
                return ResourceManager.GetString("AddComplaints.ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تقديم بلاغ.
        /// </summary>
        public static string AddComplaints_en {
            get {
                return ResourceManager.GetString("AddComplaints.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الالكتروني تم استخدامه من قبل.
        /// </summary>
        public static string EmailIsExist_ar {
            get {
                return ResourceManager.GetString("EmailIsExist.ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email number has already been used.
        /// </summary>
        public static string EmailIsExist_en {
            get {
                return ResourceManager.GetString("EmailIsExist.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف غير موجوده.
        /// </summary>
        public static string ErrorEmail_ar {
            get {
                return ResourceManager.GetString("ErrorEmail.ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number does not exist.
        /// </summary>
        public static string ErrorEmail_en {
            get {
                return ResourceManager.GetString("ErrorEmail.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   رقم الهاتف او كلمة المرور غير صحيحه.
        /// </summary>
        public static string ErrorLogin_ar {
            get {
                return ResourceManager.GetString("ErrorLogin.ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number, or password is incorrect.
        /// </summary>
        public static string ErrorLogin_en {
            get {
                return ResourceManager.GetString("ErrorLogin.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسيت كلمة مرور.
        /// </summary>
        public static string ForgotPassword_ar {
            get {
                return ResourceManager.GetString("ForgotPassword.ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPassword_en {
            get {
                return ResourceManager.GetString("ForgotPassword.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert security code.
        /// </summary>
        public static string InsertOPTCode {
            get {
                return ResourceManager.GetString("InsertOPTCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجاء إدخال رمز الحماية.
        /// </summary>
        public static string InsertOPTCode_ar {
            get {
                return ResourceManager.GetString("InsertOPTCode.ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التقديم بنجاح.
        /// </summary>
        public static string InsertSuccess_ar {
            get {
                return ResourceManager.GetString("InsertSuccess.ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted successfully.
        /// </summary>
        public static string InsertSuccess_en {
            get {
                return ResourceManager.GetString("InsertSuccess.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف غير مفعل.
        /// </summary>
        public static string IsNotConfirmed_ar {
            get {
                return ResourceManager.GetString("IsNotConfirmed.ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone No is not confirmed.
        /// </summary>
        public static string IsNotConfirmed_en {
            get {
                return ResourceManager.GetString("IsNotConfirmed.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدخول.
        /// </summary>
        public static string Login_ar {
            get {
                return ResourceManager.GetString("Login.ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_en {
            get {
                return ResourceManager.GetString("Login.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم الوطني مسجل سابقاً.
        /// </summary>
        public static string NationalIdExist_ar {
            get {
                return ResourceManager.GetString("NationalIdExist.ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The National Id has already been used.
        /// </summary>
        public static string NationalIdExist_en {
            get {
                return ResourceManager.GetString("NationalIdExist.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايوجد معلومات مرتبطة بهذا الحساب.
        /// </summary>
        public static string NoAccountInfo_ar {
            get {
                return ResourceManager.GetString("NoAccountInfo.ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no information associated with this account.
        /// </summary>
        public static string NoAccountInfo_en {
            get {
                return ResourceManager.GetString("NoAccountInfo.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسجيل.
        /// </summary>
        public static string Register_ar {
            get {
                return ResourceManager.GetString("Register.ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register_en {
            get {
                return ResourceManager.GetString("Register.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التسجيل بنجاح.
        /// </summary>
        public static string RegisterSuccess_ar {
            get {
                return ResourceManager.GetString("RegisterSuccess.ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Registered.
        /// </summary>
        public static string RegisterSuccess_en {
            get {
                return ResourceManager.GetString("RegisterSuccess.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز الحماية غير صحيح.
        /// </summary>
        public static string SecurityCode_ar {
            get {
                return ResourceManager.GetString("SecurityCode.ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect security code.
        /// </summary>
        public static string SecurityCode_en {
            get {
                return ResourceManager.GetString("SecurityCode.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إرسال رمز التأكيد.
        /// </summary>
        public static string SendOTP_ar {
            get {
                return ResourceManager.GetString("SendOTP.ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation code sent.
        /// </summary>
        public static string SendOTP_en {
            get {
                return ResourceManager.GetString("SendOTP.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث كلمة مرور.
        /// </summary>
        public static string UpdatePassword_ar {
            get {
                return ResourceManager.GetString("UpdatePassword.ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Password.
        /// </summary>
        public static string UpdatePassword_en {
            get {
                return ResourceManager.GetString("UpdatePassword.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث الرمز.
        /// </summary>
        public static string UpdateToken_ar {
            get {
                return ResourceManager.GetString("UpdateToken.ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Token.
        /// </summary>
        public static string UpdateToken_en {
            get {
                return ResourceManager.GetString("UpdateToken.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث معلومات المستخدم.
        /// </summary>
        public static string UpdateUser_ar {
            get {
                return ResourceManager.GetString("UpdateUser.ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update User.
        /// </summary>
        public static string UpdateUser_en {
            get {
                return ResourceManager.GetString("UpdateUser.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التحديث بنجاح.
        /// </summary>
        public static string UpdateUserSuccess_ar {
            get {
                return ResourceManager.GetString("UpdateUserSuccess.ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Updated.
        /// </summary>
        public static string UpdateUserSuccess_en {
            get {
                return ResourceManager.GetString("UpdateUserSuccess.en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المسنخدم غير موجود.
        /// </summary>
        public static string UserNotExsit_ar {
            get {
                return ResourceManager.GetString("UserNotExsit.ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not exsit.
        /// </summary>
        public static string UserNotExsit_en {
            get {
                return ResourceManager.GetString("UserNotExsit.en", resourceCulture);
            }
        }
    }
}
